# Generated by Django 3.0.3 on 2020-02-10 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=50)),
                ('accountType', models.CharField(choices=[('biezace', 'Rachunek bierzący'), ('oszczednosciowe', 'Oszczędnościowe')], default='biezace', max_length=20)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='zł', max_length=5)),
                ('is_default', models.BooleanField(default=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('income', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_cyclic', models.BooleanField()),
                ('topped_up_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Jedzenie', 'Jedzenie'), ('Chemia', 'Chemia'), ('Kosmetyki_Higiena_Leki', 'Kosmetyki, środki higieniczne i lekarstwa'), ('Dom', 'Dom'), ('Transport', 'Transport'), ('Inne', 'Inne')], default='Jedzenie', max_length=50)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.FloatField()),
                ('unit_name', models.CharField(choices=[('szt', 'szt'), ('kg', 'kg'), ('l', 'l')], default='szt', max_length=5)),
                ('currency', models.CharField(default='zł', max_length=5)),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('charged_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
    ]
