# Generated by Django 3.0.3 on 2020-02-11 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_debt', models.FloatField()),
                ('debt_left', models.FloatField()),
                ('repayment', models.FloatField()),
                ('repayment_date', models.DateField()),
                ('number_of_installments', models.IntegerField()),
                ('installments_payed', models.IntegerField()),
                ('interests', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
    ]
