# Generated by Django 3.0.3 on 2020-02-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_credits_repayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='installments_payed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('planned_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
    ]
