# Generated by Django 3.0.3 on 2020-02-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200212_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='category',
            field=models.CharField(choices=[('Jedzenie', 'Jedzenie'), ('Chemia', 'Chemia'), ('Kosmetyki_Higiena_Leki', 'Kosmetyki, środki higieniczne i lekarstwa'), ('Dom', 'Dom'), ('Transport', 'Transport'), ('Inne', 'Inne')], default='Jedzenie', max_length=50),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='unit_name',
            field=models.CharField(choices=[('szt', 'szt'), ('kg', 'kg'), ('l', 'l')], default='szt', max_length=5),
        ),
    ]
