# Generated by Django 3.0.3 on 2020-02-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_plan_predicted_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregularPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('category', models.CharField(choices=[('Jedzenie', 'Jedzenie'), ('Chemia', 'Chemia'), ('Kosmetyki_Higiena_Leki', 'Kosmetyki, środki higieniczne i lekarstwa'), ('Dom', 'Dom'), ('Transport', 'Transport'), ('Inne', 'Inne')], default='Inne', max_length=50)),
                ('charged_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Accounts')),
            ],
        ),
    ]
