# Generated by Django 3.0.3 on 2020-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_unregularplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregularplan',
            name='realized',
            field=models.BooleanField(default=False),
        ),
    ]
